name = "Knuckledragger"
uuid = "0ff7cecf-e0d4-4c8f-bb74-7c8410ff30b2"
authors = ["Philip Zucker"]
version = "1.0.0-DEV"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
CondaPkg = "0.2.24"
PythonCall = "0.9.23"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
